"""
closet_taxonomy.py — augment closets with fixed-vocabulary classification.

The prose closets generated by ``closet_llm`` describe a file using
content-grounded vocabulary (the function names, types, and verbs the
file itself uses). This works well for queries phrased in the same
register, but fails for paraphrased / abstract queries — e.g., a file
whose closet says "JSON-RPC client for MemPalace MCP server" will not
match a query like "black-box integration of external service" because
the vocabulary doesn't overlap.

This module fills that gap by asking the LLM to *classify* each file
against a FIXED TAXONOMY of abstract architectural terms (wrapper,
adapter, gate, external_service, source_of_truth, tiered_pipeline,
boundary, etc). The LLM doesn't have to invent vocabulary — it just
picks 2-4 labels per category from a closed list. Even small models
(Qwen2.5-3B) are reliable at this classification task.

The picked labels are converted into 4 natural-language sentences per
file and appended to the closets collection. These sentences are
ADDITIVE — they never replace the prose closets from ``closet_llm``.
Both layers contribute to retrieval through the existing hybrid
scorer in ``searcher.search_within``.

## Use

  python -m mempalace.closet_taxonomy --palace ~/.mempalace/palace

Configuration falls through to ``MempalaceConfig`` for LLM endpoint /
model just like ``closet_llm``. The ``--sample N`` flag is provided for
bench runs; production use processes every source file in the palace.

## Why this is a separate module

Classification is a different concern from prose generation. It uses a
different prompt, a closed vocabulary, and runs on its own cadence —
classify-once-and-keep semantics rather than re-summarise-on-update.
Keeping it separate also means a regen of prose closets doesn't blow
away the taxonomy rows, and vice versa.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
import urllib.error
import urllib.request
from datetime import datetime
from typing import Optional

from .closet_llm import LLMConfig
from .config import MempalaceConfig
from .palace import (
    NORMALIZE_VERSION,
    get_closets_collection,
    get_collection,
    mine_lock,
)
from .parallel import ParallelPipeline, WorkerResult

MAX_CONTENT_CHARS = 8000  # smaller than closet_llm — classification needs less context
MAX_OUTPUT_TOKENS = 300
HTTP_TIMEOUT_S = int(os.environ.get("MEMPALACE_LLM_HTTP_TIMEOUT_S", "600"))

# Fixed taxonomy. Closed vocabulary — LLM picks from these, doesn't
# invent. Curated to include the abstract terms that bridge from
# content-grounded prose closets to paraphrased queries.
#
# Add to this taxonomy when you find a query that systematically misses
# its target — the term you would have wanted in the closet probably
# belongs in one of these lists.
TAXONOMY = {
    "structural_role": [
        "wrapper", "adapter", "facade", "gate", "parser", "ledger",
        "registry", "catalog", "client", "server", "subprocess",
        "controller", "dispatcher", "orchestrator", "worker", "producer",
        "consumer", "hook", "handler", "factory", "builder", "validator",
        "design_doc", "spec", "plan", "readme", "runbook", "test",
        "config", "migration", "black_box",
    ],
    "function": [
        "search", "retrieve", "fetch", "ingest", "mine", "generate",
        "render", "transform", "summarize", "classify", "rank", "filter",
        "deduplicate", "validate", "parse", "serialize", "dispatch",
        "route", "orchestrate", "integrate", "tier", "score",
    ],
    "abstraction": [
        "pipeline", "tiered_pipeline", "layer", "tier", "contract",
        "interface", "boundary", "source_of_truth", "authoritative",
        "external_service", "black_box", "internal", "public_api",
        "infrastructure", "application", "ui", "cli", "backend",
        "frontend", "verbatim_storage", "index", "metadata",
    ],
}


CLASSIFY_PROMPT = """You are classifying a file's role using a FIXED VOCABULARY.

Look at the CONTENT below. From each list, pick the 2-4 labels that BEST
describe what this file IS or DOES. Pick labels ONLY from the lists.
Do not invent new labels.

STRUCTURAL_ROLE — what kind of artifact this is:
{structural_role}

FUNCTION — what this file does:
{function}

ABSTRACTION — what level/role this operates at:
{abstraction}

────────────────────────────────────────────────────────────────────
SPECIFICITY RULE (most important):

When multiple labels apply, PREFER THE SPECIFIC ONE over the generic one.

• If the file talks to a service or system OUTSIDE the local Python code
  (HTTP API, subprocess, database, file system as an IPC channel), pick
  `external_service` and `boundary` — NOT just `backend`.

• If the file hides implementation behind a simple interface so callers
  treat it as a sealed unit, pick `black_box` and `wrapper`.

• If the file routes work through STAGES with different cost/quality
  tradeoffs (cheap first, expensive fallback, ranked retrieval), pick
  `tiered_pipeline` — NOT just `pipeline`.

• If the file is the AUTHORITATIVE record / canonical truth for something
  (the implementation that owns state, the canonical config, the decision
  log), pick `source_of_truth` and `authoritative`.

Generic labels (`backend`, `internal`, `application`) are LAST RESORT. If
a more specific label fits, use it instead.

WORKED EXAMPLE — for a Python file that spawns a subprocess, sends JSON-RPC,
parses responses, and provides a clean Python API to callers:

  structural_role: ["wrapper", "client", "adapter"]
  function: ["fetch", "serialize", "integrate", "dispatch"]
  abstraction: ["external_service", "black_box", "boundary"]

NOT ["client"], ["fetch"], ["backend"]. The specific labels are what matter.

────────────────────────────────────────────────────────────────────

Source: {source_file}

CONTENT:
{content}

---

Output JSON only. Pick 2-4 labels per category. Use only labels from the
lists above. Prefer specific labels per the SPECIFICITY RULE above. No
commentary, no code fences.

{{
  "structural_role": ["label1", "label2"],
  "function": ["label1", "label2"],
  "abstraction": ["label1", "label2"]
}}
"""


def _call_classifier(cfg: LLMConfig, source_file: str, content: str):
    """Single classification call. Returns (parsed_dict_or_None, usage_or_None)."""
    prompt = CLASSIFY_PROMPT.format(
        structural_role=", ".join(TAXONOMY["structural_role"]),
        function=", ".join(TAXONOMY["function"]),
        abstraction=", ".join(TAXONOMY["abstraction"]),
        source_file=os.path.basename(source_file)[:60],
        content=content[:MAX_CONTENT_CHARS],
    )
    body = json.dumps(
        {
            "model": cfg.model,
            "max_tokens": MAX_OUTPUT_TOKENS,
            "temperature": 0.1,
            "messages": [{"role": "user", "content": prompt}],
        }
    ).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if cfg.key:
        headers["Authorization"] = f"Bearer {cfg.key}"
    url = f"{cfg.endpoint}/chat/completions"

    for attempt in range(3):
        try:
            req = urllib.request.Request(url, data=body, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_S) as resp:
                raw = resp.read().decode("utf-8")
            payload = json.loads(raw)
            text = payload["choices"][0]["message"]["content"].strip()
            text = re.sub(r"^```(?:json)?\s*", "", text)
            text = re.sub(r"\s*```$", "", text)
            return json.loads(text), payload.get("usage")
        except json.JSONDecodeError:
            return None, None
        except urllib.error.HTTPError as e:
            if e.code in (429, 503) and attempt < 2:
                time.sleep(2**attempt)
                continue
            return None, None
        except Exception as e:
            if "rate" in str(e).lower() and attempt < 2:
                time.sleep(2**attempt)
                continue
            return None, None
    return None, None


def _filter_labels(labels, vocab) -> list:
    """Keep only labels present in the fixed vocabulary; cap at 4."""
    if not isinstance(labels, list):
        return []
    vocab_set = set(vocab)
    return [lab for lab in labels if isinstance(lab, str) and lab in vocab_set][:4]


def _labels_to_sentences(source_file: str, classified: dict) -> list:
    """Build 2-4 natural sentences from classification labels.

    Each sentence uses the labels in NATURAL phrases (e.g. "is a wrapper
    that operates as external service and boundary"), not stiff list-style
    ("Abstractions this file embodies: black_box, external_service").
    Natural phrasing embeds much better against natural-language queries.
    """
    basename = os.path.basename(source_file)
    sr = _filter_labels(classified.get("structural_role", []), TAXONOMY["structural_role"])
    fn = _filter_labels(classified.get("function", []), TAXONOMY["function"])
    ab = _filter_labels(classified.get("abstraction", []), TAXONOMY["abstraction"])

    def humanize(label: str) -> str:
        return label.replace("_", " ")

    sr_h = [humanize(s) for s in sr]
    fn_h = [humanize(f) for f in fn]
    ab_h = [humanize(a) for a in ab]

    sentences = []

    # Sentence 1: primary role + primary abstraction in natural phrasing.
    if sr_h and ab_h:
        primary_role = sr_h[0]
        article = "an" if primary_role[:1].lower() in "aeiou" else "a"
        ab_phrase = ab_h[0] + (f" and {ab_h[1]}" if len(ab_h) > 1 else "")
        sentences.append(
            f"{basename} is {article} {primary_role} that operates as {ab_phrase}."
        )

    # Sentence 2: combine all three categories.
    if sr_h and fn_h and ab_h:
        roles = " and ".join(sr_h[:2])
        fns = " and ".join(fn_h[:2])
        sentences.append(
            f"This file acts as a {roles} to {fns} across the {ab_h[0]} boundary."
        )

    # Sentence 3: abstractions in natural prose.
    if ab_h:
        if len(ab_h) >= 2:
            tail = f", with elements of {ab_h[2]}" if len(ab_h) > 2 else ""
            sentences.append(f"The file functions as {ab_h[0]} and {ab_h[1]}{tail}.")
        else:
            sentences.append(f"The file functions as {ab_h[0]}.")

    # Sentence 4: role-centric, treats functions as verbs.
    if sr_h and fn_h:
        fn1 = fn_h[0]
        fn2 = fn_h[1] if len(fn_h) > 1 else fn_h[0]
        sentences.append(
            f"The {sr_h[0]} handles {fn1} and {fn2} on behalf of callers."
        )

    return sentences


def _source_hash(source_file: str) -> str:
    """Short deterministic hash of the full source_file path.

    Used as the row-id stem so re-running the augmenter upserts replace
    rather than accumulate, AND so two files with the same basename in
    different directories don't collide on ID.
    """
    return hashlib.sha256(source_file.encode("utf-8")).hexdigest()[:16]


def augment_palace(
    palace_path: str,
    wing: Optional[str] = None,
    sample: int = 0,
    dry_run: bool = False,
    cfg: Optional[LLMConfig] = None,
    workers: Optional[int] = None,
):
    """Classify every source file in the palace and add taxonomy closet rows.

    The taxonomy rows are additive — prose closets from
    ``closet_llm.regenerate_closets`` are preserved. Re-running this
    function REPLACES taxonomy rows for each processed source (via
    deterministic IDs); prose rows are untouched.

    Returns a stats dict — ``processed``, ``failed``, ``input_tokens``,
    ``output_tokens``.
    """
    if cfg is None:
        cfg = LLMConfig()
    missing = cfg.missing()
    if missing:
        print("Error: missing configuration: " + ", ".join(missing))
        print("Set env vars LLM_ENDPOINT / LLM_MODEL (and optionally LLM_KEY),")
        print("or pass --endpoint / --model / --key on the CLI.")
        return {"error": "missing-config", "missing": missing}

    drawers_col = get_collection(palace_path, create=False)
    closets_col = get_closets_collection(palace_path)

    total = drawers_col.count()
    if total == 0:
        print("No drawers in palace.")
        return {"processed": 0}

    # Page through drawers to collect content per source_file. Same
    # 10K/page bound as closet_llm to stay under SQLite's variable limit.
    by_source: dict = {}
    PAGE = 10000
    offset = 0
    while offset < total:
        page = drawers_col.get(limit=PAGE, offset=offset, include=["documents", "metadatas"])
        for doc_id, doc, meta in zip(page["ids"], page["documents"], page["metadatas"]):
            source = (meta or {}).get("source_file", "unknown")
            w = (meta or {}).get("wing", "")
            if wing and w != wing:
                continue
            if source not in by_source:
                by_source[source] = {"drawer_ids": [], "content": [], "meta": meta}
            by_source[source]["drawer_ids"].append(doc_id)
            by_source[source]["content"].append(doc)
        offset += PAGE

    sources = list(by_source.keys())
    if sample > 0:
        sources = sources[:sample]

    print(
        f"Classifying {len(sources)} source files via {cfg.endpoint} ({cfg.model})..."
    )
    if dry_run:
        print("DRY RUN — no changes will be written")
        for i, source in enumerate(sources, 1):
            data = by_source[source]
            content = "\n\n".join(data["content"])
            print(f"  [{i}/{len(sources)}] {os.path.basename(source)} ({len(content)} chars)")
        return {"processed": 0, "failed": 0, "input_tokens": 0, "output_tokens": 0}

    if workers is None:
        workers = MempalaceConfig().workers

    processed = 0
    failed = 0
    total_input = 0
    total_output = 0

    def producer(item):
        idx, source = item
        data = by_source[source]
        content = "\n\n".join(data["content"])
        meta = data["meta"] or {}
        parsed, usage = _call_classifier(cfg, source, content)
        return WorkerResult(
            payload={
                "parsed": parsed,
                "usage": usage,
                "drawer_ids": data["drawer_ids"],
                "wing": meta.get("wing", ""),
                "room": meta.get("room", ""),
                "entities": meta.get("entities", ""),
                "source": source,
            },
            item_id=os.path.basename(source),
            extra={"idx": idx, "total": len(sources)},
        )

    def consumer(result):
        nonlocal processed, failed, total_input, total_output
        p = result.payload
        idx = result.extra["idx"]
        total = result.extra["total"]

        if not p["parsed"]:
            failed += 1
            print(f"  [{idx}/{total}] ✗ {result.item_id} — classification failed")
            return

        if p["usage"]:
            total_input += p["usage"].get("prompt_tokens", 0)
            total_output += p["usage"].get("completion_tokens", 0)

        sentences = _labels_to_sentences(p["source"], p["parsed"])
        if not sentences:
            failed += 1
            print(f"  [{idx}/{total}] ✗ {result.item_id} — empty classification")
            return

        drawer_ref = ",".join(p["drawer_ids"][:3])
        fid = _source_hash(p["source"])

        rows = []
        ids = []
        metas = []
        for i, sent in enumerate(sentences):
            line = f"{sent[:280]}|{p['entities']}|→{drawer_ref}"
            rows.append(line)
            ids.append(f"taxonomy_{fid}_{i}")
            metas.append(
                {
                    "wing": p["wing"],
                    "room": p["room"],
                    "source_file": p["source"],
                    "generated_by": "taxonomy:v2",
                    "filed_at": datetime.now().isoformat(),
                    "entities": p["entities"],
                    "normalize_version": NORMALIZE_VERSION,
                }
            )

        # mine_lock to serialize against any concurrent mine of the same
        # source. Taxonomy rows are *additive* to prose closets — we
        # never purge generated_by="llm:*" rows here.
        with mine_lock(p["source"]):
            # Deterministic IDs mean upsert replaces prior taxonomy rows
            # for this source. Prose rows are untouched.
            closets_col.upsert(documents=rows, ids=ids, metadatas=metas)

        processed += 1
        n = len(sentences)
        print(f"  [{idx}/{total}] ✓ {result.item_id} — {n} taxonomy rows")

    def on_error(failed_result):
        nonlocal failed
        failed += 1
        print(
            f"  ✗ {failed_result.item_id} — {type(failed_result.exception).__name__}: "
            f"{failed_result.exception}"
        )

    pipeline = ParallelPipeline(
        producer_fn=producer,
        consumer_fn=consumer,
        workers=workers,
        queue_size=max(workers * 2, 4),
        on_error=on_error,
    )
    pipeline.run(list(enumerate(sources, 1)))

    print(f"\nDone. {processed} classified, {failed} failed.")
    if total_input or total_output:
        print(f"Tokens: {total_input:,} in + {total_output:,} out")

    return {
        "processed": processed,
        "failed": failed,
        "input_tokens": total_input,
        "output_tokens": total_output,
    }


if __name__ == "__main__":
    import argparse
    from .config import DEFAULT_PALACE_PATH

    parser = argparse.ArgumentParser(
        description="Augment closets with fixed-vocabulary classification "
        "to bridge paraphrased queries to their target files."
    )
    parser.add_argument("--palace", default=DEFAULT_PALACE_PATH, help="Path to palace")
    parser.add_argument("--wing", default=None, help="Limit to one wing")
    parser.add_argument("--sample", type=int, default=0, help="Only process first N sources")
    parser.add_argument("--dry-run", action="store_true", help="List work without LLM calls")
    parser.add_argument("--workers", type=int, default=None, help="Producer threads")
    parser.add_argument("--endpoint", default=None, help="LLM base URL (overrides $LLM_ENDPOINT)")
    parser.add_argument("--key", default=None, help="LLM bearer token (overrides $LLM_KEY)")
    parser.add_argument("--model", default=None, help="LLM model name (overrides $LLM_MODEL)")
    args = parser.parse_args()

    cfg = LLMConfig(endpoint=args.endpoint, key=args.key, model=args.model)
    augment_palace(
        args.palace,
        wing=args.wing,
        sample=args.sample,
        dry_run=args.dry_run,
        cfg=cfg,
        workers=args.workers,
    )
